"""
Tests for openfde.prs — Land as PR v1: branch slugs, the story-as-PR-body builder,
and create_episode_pr's guardrails (idempotent, clean-worktree gate, gh missing/
unauthenticated, branch reuse/suffix, push/PR failure) with a scripted runner —
no git mutation, no network, no real gh.
"""

import unittest

from openfde.prs import branch_slug, build_pr_text, create_episode_pr

SHA = "a" * 40


def _episode(**over):
    base = {
        "episodeId": "episode_pr1", "tag": "P25", "title": "Verify Gate Evidence",
        "summary": "Receipts before landing: local checks gate Auto-Land.",
        "status": "landed",
        "commitShas": [SHA],
        "commitMeta": {SHA: {"title": "Verify Gate Evidence", "summary": "gate + receipts"}},
        "files": ["openfde/verify.py", "openfde/autoland.py"],
        "verify": {"status": "passed", "checks": [
            {"id": "unit-tests", "label": "Unit tests", "status": "passed",
             "summary": "Ran 173 tests in 12.5s — OK"},
            {"id": "frontend-lint", "label": "Frontend lint", "status": "passed",
             "summary": "> eslint ."},
        ]},
        "intentSource": {"provider": "github", "issueNumber": 42,
                         "url": "https://github.com/acme/repo/issues/42",
                         "title": "Trust the land", "state": "OPEN", "labels": []},
    }
    base.update(over)
    return base


class FakeProc:
    def __init__(self, stdout="", returncode=0, stderr=""):
        self.stdout, self.returncode, self.stderr = stdout, returncode, stderr


def scripted_runner(script):
    """Pop one canned FakeProc per call; record every command. Raises if exhausted."""
    queue = list(script)
    calls = []

    def run(cmd, **kw):
        calls.append(cmd)
        item = queue.pop(0)
        if isinstance(item, Exception):
            raise item
        return item

    run.calls = calls
    return run


CLEAN = FakeProc(stdout="")                       # git status --porcelain
SYMREF = FakeProc(stdout="origin/main\n")         # git symbolic-ref origin/HEAD
NOT_MERGED = FakeProc(returncode=1)               # merge-base --is-ancestor → not on base
MERGED = FakeProc(returncode=0)                   # merge-base --is-ancestor → already on base
AUTH_OK = FakeProc(stdout="Logged in")            # gh auth status
NO_BRANCH = FakeProc(returncode=1)                # git rev-parse (branch missing)
MK_OK = FakeProc()                                # git branch
PUSH_OK = FakeProc()                              # git push
PR_OK = FakeProc(stdout="https://github.com/acme/repo/pull/123\n")
GUARD = [SYMREF, NOT_MERGED]                      # base resolved + head not yet merged


class SlugTest(unittest.TestCase):
    def test_predictable_branch_name(self):
        self.assertEqual(branch_slug(_episode()), "openfde/p25-verify-gate-evidence")

    def test_slug_sanitizes_and_caps(self):
        ep = _episode(tag="P7!", title="Fix: the (very) Long & Strange — title " + "x" * 80)
        s = branch_slug(ep)
        self.assertTrue(s.startswith("openfde/p7-fix-the-very-long-strange-title"))
        self.assertLessEqual(len(s), len("openfde/p7-") + 40)
        self.assertNotIn("--", s.replace("openfde/", "", 1).split("-", 1)[0])

    def test_missing_bits_still_valid(self):
        self.assertEqual(branch_slug({}), "openfde/ep-episode")


class BodyTest(unittest.TestCase):
    def test_body_carries_story_and_receipts(self):
        title, body = build_pr_text(_episode())
        self.assertEqual(title, "Verify Gate Evidence")
        self.assertIn("## P25 · Verify Gate Evidence", body)
        self.assertIn("Receipts before landing", body)                 # story summary
        self.assertIn("**Issue:** #42 — https://github.com/acme/repo/issues/42", body)
        self.assertIn(f"`{SHA[:7]}` — Verify Gate Evidence", body)     # commit + durable title
        self.assertIn("`openfde/verify.py`", body)                     # files
        self.assertIn("**Verification:** ✅ passed", body)
        self.assertIn("✅ Unit tests — Ran 173 tests in 12.5s — OK", body)
        self.assertIn("Generated by OpenFDE from episode P25", body)

    def test_files_capped(self):
        ep = _episode(files=[f"f{i}.py" for i in range(40)])
        _, body = build_pr_text(ep)
        self.assertIn("**Files (40):**", body)
        self.assertIn("… +10 more", body)

    def test_skipped_verification_is_explicit(self):
        ep = _episode(verify={"status": "skipped", "checks": [],
                              "note": "verification not configured — no checks discovered"})
        _, body = build_pr_text(ep)
        self.assertIn("**Verification:** ⏭️ skipped", body)
        self.assertIn("not configured", body)


class CreatePrTest(unittest.TestCase):
    def test_existing_pr_is_idempotent_and_calls_nothing(self):
        run = scripted_runner([])                                       # any call would raise
        ep = _episode(pr={"provider": "github", "number": 9,
                          "url": "https://github.com/acme/repo/pull/9"})
        res = create_episode_pr("/r", ep, runner=run)
        self.assertTrue(res["ok"]) and self.assertTrue(res["existing"])
        self.assertEqual(res["pr"]["number"], 9)
        self.assertEqual(run.calls, [])

    def test_no_commits_blocks(self):
        res = create_episode_pr("/r", _episode(commitShas=[]), runner=scripted_runner([]))
        self.assertFalse(res["ok"])
        self.assertIn("no landed commits", res["error"])

    def test_dirty_worktree_blocks(self):
        run = scripted_runner([FakeProc(stdout=" M openfde/server.py\n")])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("dirty", res["error"])

    def test_gh_missing_is_structured_error(self):
        run = scripted_runner([CLEAN, *GUARD, FileNotFoundError("gh")])
        ep = _episode()
        res = create_episode_pr("/r", ep, runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("gh CLI not installed", res["error"])
        self.assertNotIn("pr", ep)                                      # episode untouched

    def test_gh_unauthenticated(self):
        run = scripted_runner([CLEAN, *GUARD, FakeProc(returncode=1, stderr="not logged in")])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("not authenticated", res["error"])

    def test_already_merged_commit_blocks_before_any_mutation(self):
        # The user-reported gap: episode commits already pushed to origin/main would
        # make an empty/no-diff PR. The guard refuses BEFORE branch/push/gh.
        run = scripted_runner([CLEAN, SYMREF, MERGED])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn(f"episode commit {SHA[:7]} is already on origin/main", res["error"])
        self.assertIn("no PR needed", res["error"])
        self.assertEqual(len(run.calls), 3)                             # nothing else ran
        self.assertFalse(any(c[0] == "gh" for c in run.calls))          # gh never touched

    def test_base_falls_back_to_origin_main_when_no_origin_head(self):
        # symbolic-ref fails (no origin/HEAD) → rev-parse origin/main resolves the base.
        run = scripted_runner([CLEAN, FakeProc(returncode=1), FakeProc(stdout=SHA + "\n"),
                               MERGED])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("already on origin/main", res["error"])

    def test_no_remote_tracking_ref_skips_guard(self):
        # No origin/HEAD, no origin/main, no origin/master → guard skipped, flow continues
        # (a later push surfaces its own error on a truly remote-less repo).
        run = scripted_runner([CLEAN, FakeProc(returncode=1), FakeProc(returncode=1),
                               FakeProc(returncode=1), AUTH_OK, NO_BRANCH, MK_OK, PUSH_OK, PR_OK])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertTrue(res["ok"])
        self.assertEqual(res["pr"]["number"], 123)

    def test_happy_path_creates_branch_pushes_and_parses_pr(self):
        run = scripted_runner([CLEAN, *GUARD, AUTH_OK, NO_BRANCH, MK_OK, PUSH_OK, PR_OK])
        res = create_episode_pr("/r", _episode(), runner=run, now="2026-06-09T23:00:00Z")
        self.assertTrue(res["ok"])
        pr = res["pr"]
        self.assertEqual(pr["number"], 123)
        self.assertEqual(pr["url"], "https://github.com/acme/repo/pull/123")
        self.assertEqual(pr["branch"], "openfde/p25-verify-gate-evidence")
        self.assertEqual(pr["state"], "OPEN")
        self.assertEqual(pr["createdAt"], "2026-06-09T23:00:00Z")
        # command shape: status, symref, merge-base, auth, rev-parse, branch, push, create.
        self.assertEqual(run.calls[2][:2], ["git", "merge-base"])
        self.assertEqual(run.calls[5][:2], ["git", "branch"])
        self.assertEqual(run.calls[5][3], SHA)                          # branch AT the episode head
        self.assertEqual(run.calls[6][:4], ["git", "push", "-u", "origin"])
        self.assertEqual(run.calls[7][:3], ["gh", "pr", "create"])
        self.assertIn("--title", run.calls[7])

    def test_existing_branch_same_commit_reused(self):
        run = scripted_runner([CLEAN, *GUARD, AUTH_OK, FakeProc(stdout=SHA + "\n"), PUSH_OK, PR_OK])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertTrue(res["ok"])
        self.assertEqual(res["pr"]["branch"], "openfde/p25-verify-gate-evidence")
        self.assertFalse(any(c[:2] == ["git", "branch"] for c in run.calls))   # no new branch

    def test_existing_branch_other_commit_gets_suffix(self):
        run = scripted_runner([CLEAN, *GUARD, AUTH_OK, FakeProc(stdout="b" * 40 + "\n"),
                               NO_BRANCH, MK_OK, PUSH_OK, PR_OK])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertTrue(res["ok"])
        self.assertEqual(res["pr"]["branch"],
                         f"openfde/p25-verify-gate-evidence-{SHA[:7]}")

    def test_push_failure_returns_evidence(self):
        run = scripted_runner([CLEAN, *GUARD, AUTH_OK, NO_BRANCH, MK_OK,
                               FakeProc(returncode=1, stderr="remote: denied")])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("push failed", res["error"])
        self.assertIn("denied", res["error"])
        self.assertEqual(res["branch"], "openfde/p25-verify-gate-evidence")
        self.assertFalse(res["pushed"])

    def test_gh_create_failure_after_push(self):
        run = scripted_runner([CLEAN, *GUARD, AUTH_OK, NO_BRANCH, MK_OK, PUSH_OK,
                               FakeProc(returncode=1, stderr="pull request create failed")])
        res = create_episode_pr("/r", _episode(), runner=run)
        self.assertFalse(res["ok"])
        self.assertIn("gh pr create failed", res["error"])
        self.assertTrue(res["pushed"])                                  # evidence for Review


if __name__ == "__main__":
    unittest.main()
