"""
openfde/echo_transport.py — offline "echo" agent transport (Step 22a demo).

Lets you watch the full native-agent loop run in the UI with NO API key and NO
network: draw a dotted box → Execute (openfde-agent) → the echo agent makes one
small, safe, reversible edit to the first editable file → it flows through the
real diff / commit / canvas / timeline / ledger / box-spec path.

It implements the same transport contract as anthropic_transport: it returns
tool_use blocks the runner executes. The edit is a single comment marker chosen
to match the file's language so it stays syntactically valid; JSON (which has no
comments) gets a harmless trailing newline instead.
"""

from datetime import datetime, timezone
from pathlib import Path

# Extension → line-comment style.
_SLASH = {"js", "jsx", "ts", "tsx", "mjs", "cjs", "go", "rs", "java", "c", "cc",
          "cpp", "h", "hpp", "kt", "swift", "scala", "php"}
_BLOCK = {"css", "scss", "less"}
_HTMLISH = {"html", "htm", "xml", "md", "markdown", "svg", "vue"}


def _ext(path: str) -> str:
    return path.rsplit(".", 1)[-1].lower() if "." in path else ""


def _marked_content(path: str, current: str, iso: str) -> str:
    """Return `current` with a language-appropriate demo marker appended."""
    ext = _ext(path)
    text = f"openfde echo agent — demo edit {iso}"
    base = current.rstrip("\n")
    if ext == "json":
        # JSON has no comments — a trailing newline is a harmless, valid diff.
        return current if current.endswith("\n\n") else (current.rstrip("\n") + "\n\n")
    if ext in _SLASH:
        line = f"// {text}"
    elif ext in _BLOCK:
        line = f"/* {text} */"
    elif ext in _HTMLISH:
        line = f"<!-- {text} -->"
    else:                       # py, sh, yaml, toml, unknown → '#'
        line = f"# {text}"
    return f"{base}\n{line}\n" if base else f"{line}\n"


# ── Support-inbox demo scaffold ─────────────────────────────────────────────
# When the keyless echo run is driving the "AI support inbox" sketch, it writes a
# tiny-but-plausible SaaS backend — one readable file per step — instead of the
# generic marker, so each intent box grounds into its OWN credible file. This is a
# DEMO fixture (deterministic, no network, no model): the recognition is by the
# selected step titles and the whole thing stays isolated in this transport layer.

_INBOX_INIT = '''"""support_inbox — a tiny AI support-inbox backend.

Generated by OpenFDE's offline **echo demo** from a sketched intent flow
(ingest -> classify -> draft -> review -> log). Deterministic and dependency-free —
an illustrative example, not production code.
"""
'''

_INBOX_INGEST = '''"""support_inbox.ingest — load and normalize incoming customer messages.

Generated by OpenFDE's offline echo demo from the sketch step "ingest customer
messages". A deterministic stand-in for a real intake stage (no network).
"""


def ingest_messages(raw_messages):
    """Normalize raw inbox payloads into clean {id, sender, text} records."""
    cleaned = []
    for i, m in enumerate(raw_messages or []):
        text = (m.get("body") or m.get("text") or "").strip()
        if not text:
            continue
        cleaned.append({
            "id": m.get("id") or f"msg-{i + 1}",
            "sender": (m.get("from") or m.get("sender") or "unknown").strip().lower(),
            "text": text,
        })
    return cleaned
'''

_INBOX_CLASSIFY = '''"""support_inbox.classify — assign an urgency and topic to a message.

Generated by OpenFDE's offline echo demo from the sketch step "classify issue".
Deterministic keyword rules — a placeholder for a real classifier / LLM call.
"""

_URGENT = ("urgent", "asap", "down", "outage", "refund", "charged", "broken")
_TOPICS = {
    "billing": ("invoice", "charge", "refund", "payment"),
    "bug": ("error", "broken", "crash", "bug"),
    "account": ("login", "password", "access", "account"),
}


def classify(message):
    """Return the message tagged with {urgency, topic} derived from its text."""
    text = (message.get("text") or "").lower()
    urgency = "high" if any(w in text for w in _URGENT) else "normal"
    topic = next((t for t, kws in _TOPICS.items() if any(k in text for k in kws)), "general")
    return {**message, "urgency": urgency, "topic": topic}
'''

_INBOX_DRAFT = '''"""support_inbox.draft — produce a suggested reply for a classified message.

Generated by OpenFDE's offline echo demo from the sketch step "draft response".
A deterministic template — a stand-in for a real reply-generation model.
"""

_OPENERS = {
    "high": "Thanks for flagging this — we're on it right away.",
    "normal": "Thanks for reaching out!",
}


def draft_reply(message):
    """Return a suggested reply string for a {text, urgency, topic} message."""
    opener = _OPENERS.get(message.get("urgency"), _OPENERS["normal"])
    topic = message.get("topic", "general")
    return (f"{opener}\\n\\n"
            f"We've logged your {topic} request and a teammate will follow up shortly.\\n\\n"
            "— Support")
'''

_INBOX_REVIEW = '''"""support_inbox.review — human review / approval gate for a drafted reply.

Generated by OpenFDE's offline echo demo from the sketch step "review approval".
Models the approve / edit / reject decision before anything is sent.
"""


def review(draft, decision="approve", edited_text=None):
    """Apply a human decision to a draft -> {status, text}.

    decision: "approve" | "edit" | "reject". An "edit" swaps in edited_text.
    """
    if decision == "reject":
        return {"status": "rejected", "text": None}
    text = edited_text if (decision == "edit" and edited_text) else draft
    return {"status": "approved", "text": text}
'''

_INBOX_LOGGING = '''"""support_inbox.logging — record how a customer issue was resolved.

Generated by OpenFDE's offline echo demo from the sketch step "log resolution".
Appends a small, deterministic resolution record (no real datastore).
"""


def log_resolution(message, review_result, store=None):
    """Append a resolution record for an approved/sent reply; return the store."""
    store = store if store is not None else []
    store.append({
        "id": message.get("id"),
        "topic": message.get("topic", "general"),
        "urgency": message.get("urgency", "normal"),
        "status": review_result.get("status", "unknown"),
        "sent": bool(review_result.get("text")),
    })
    return store
'''

# Step-role recognition: a step title hitting any keyword maps to ONE SaaS file. Ordered so the
# first match wins; keywords are broad enough to survive paraphrase ("classify issue" / "triage").
_INBOX_ROLES = [
    {"keys": ("ingest", "intake", "incoming"),            "file": "ingest.py",   "body": _INBOX_INGEST},
    {"keys": ("classif", "triage", "urgency", "categor"), "file": "classify.py", "body": _INBOX_CLASSIFY},
    {"keys": ("draft", "compose", "reply", "respons"),    "file": "draft.py",    "body": _INBOX_DRAFT},
    {"keys": ("review", "approv"),                        "file": "review.py",   "body": _INBOX_REVIEW},
    {"keys": ("log", "resolution", "resolve", "record"),  "file": "logging.py",  "body": _INBOX_LOGGING},
]


def _match_inbox_role(title: str):
    """The SaaS file role a step title maps to (first keyword hit), or None."""
    low = (title or "").lower()
    for role in _INBOX_ROLES:
        if any(k in low for k in role["keys"]):
            return role
    return None


def support_inbox_plan(steps, base_dir: str):
    """A deterministic per-step file plan for the AI support-inbox sketch, or None.

    Recognizes the sketch purely from the selected step TITLES: when ≥3 distinct inbox roles
    match, returns ``[{path, content}]`` for a small package under ``<base_dir>support_inbox/``
    (one readable file per matched step + an ``__init__``). Otherwise None, so any other sketch
    keeps the generic single-file marker. Demo-only, isolated here in the echo transport.

    Args:
        steps: list — selected intent steps ({title} dicts) or plain title strings.
        base_dir: str — the editable workspace prefix (e.g. ``openfde_work/``), '' if none.

    Returns:
        list[dict] | None — ``[{path, content}]`` files to write, or None to fall back.
    """
    if not base_dir or not steps:
        return None
    roles, seen = [], set()
    for s in steps:
        title = s.get("title") if isinstance(s, dict) else s
        role = _match_inbox_role(title or "")
        if role and role["file"] not in seen:
            seen.add(role["file"])
            roles.append(role)
    if len(roles) < 3:                          # not clearly the inbox sketch → generic marker
        return None
    pkg = f"{base_dir}support_inbox/"
    plan = [{"path": pkg + "__init__.py", "content": _INBOX_INIT}]
    plan += [{"path": pkg + r["file"], "content": r["body"]} for r in roles]
    return plan


def make_echo_transport(root, editable_files, steps=None):
    """Build an offline transport that edits the first editable file then submits.

    Args:
        root: Path | str — repository root (to read current file contents).
        editable_files: list[str] — editable, in-scope paths; the first is edited.
        steps: list | None — selected intent steps ({title}). When they look like the AI
            support-inbox sketch, the echo writes a small SaaS backend (one file per step)
            instead of the generic marker — a deterministic demo payoff (see support_inbox_plan).

    Returns:
        callable — request(dict) -> response(dict), matching the runner contract.
    """
    root = Path(root)
    target_rel = editable_files[0] if editable_files else ""
    base_dir = target_rel if target_rel.endswith("/") else ""
    # Demo payoff: a recognized SaaS sketch grounds into credible per-step files; everything else
    # keeps the original single-marker behavior (a directory scope gets a starter intent_demo.py).
    plan = support_inbox_plan(steps, base_dir)
    if not plan and target_rel.endswith("/"):
        target_rel = target_rel + "intent_demo.py"
    state = {"i": 0}

    def transport(req: dict) -> dict:
        state["i"] += 1
        if state["i"] == 1 and plan:
            writes = [{"type": "tool_use", "id": f"echo_w{i}", "name": "write_file",
                       "input": {"path": p["path"], "content": p["content"]}}
                      for i, p in enumerate(plan)]
            names = ", ".join(p["path"].rsplit("/", 1)[-1] for p in plan
                              if not p["path"].endswith("__init__.py"))
            return {
                "stop_reason": "tool_use",
                "content": [
                    {"type": "text", "text": f"Echo agent: scaffolding a small support-inbox "
                                             f"backend ({names}) — offline demo."},
                    *writes,
                ],
            }
        if state["i"] == 1 and target_rel:
            iso = datetime.now(timezone.utc).isoformat()
            try:
                current = (root / target_rel).read_text(encoding="utf-8", errors="replace")
            except OSError:
                current = ""
            new_content = _marked_content(target_rel, current, iso)
            return {
                "stop_reason": "tool_use",
                "content": [
                    {"type": "text", "text": f"Echo agent: appending a demo marker to {target_rel}."},
                    {"type": "tool_use", "id": "echo_w", "name": "write_file",
                     "input": {"path": target_rel, "content": new_content}},
                ],
            }
        summary = (f"Echo agent scaffolded a support-inbox demo backend "
                   f"({len(plan)} file[s], offline — no model call)." if plan
                   else f"Echo agent appended a demo marker to {target_rel} (offline — no model call).")
        return {
            "stop_reason": "tool_use",
            "content": [
                {"type": "tool_use", "id": "echo_s", "name": "submit_result",
                 "input": {
                     "status": "passed",
                     "reportSummary": summary,
                     "functionsChanged": [],
                     "testsRun": [],
                     "verificationResult": "skipped (echo)",
                 }},
            ],
        }

    return transport
