"""Generate a PLAN.md markdown document from canvas state and OpenPM tasks.

This is a v1 plain-text renderer.  It mirrors the structure of the frontend's
generatePlanPreview() utility so the document reads consistently whether
viewed from the right panel or from the file system.
"""

_COLUMN_LABELS: dict = {
    "todo": "To Do",
    "doing": "Doing",
    "testing": "Testing",
    "done": "Done",
}

_DEFAULT_PROMPT = "Describe what this module does..."


def generate_plan(state: dict, tasks: list, project: dict) -> str:
    """Generate a PLAN.md markdown document from canvas state and OpenPM tasks.

    Args:
        state: dict — canvas state with keys:
                      'boxes' (list[dict]) and 'arrows' (list[dict])
        tasks: list[dict] — OpenPM task list; each task has 'title', 'column',
                            'verificationStatus', 'description', 'linkedBoxIds'
        project: dict — project metadata with 'name', 'description', 'entries'

    Returns:
        str — markdown document body (UTF-8 safe, no trailing newline)
    """
    boxes: list = state.get("boxes", [])
    arrows: list = state.get("arrows", [])

    project_name: str = project.get("name") or "OpenFDE Project"
    project_desc: str = project.get("description") or ""

    # Note: intentionally no wall-clock timestamp here — PLAN.md must be a pure
    # function of canvas/tasks/project state so unchanged state yields identical
    # bytes (reloading the app must not dirty the repo).
    lines: list[str] = [
        f"# PLAN — {project_name}",
        "*Generated by OpenFDE from the canvas, tasks, and project state.*",
        "",
    ]

    if project_desc:
        lines += [project_desc, ""]

    # ------------------------------------------------------------------ #
    #  Why — module intent (box prompts)                                  #
    # ------------------------------------------------------------------ #
    why_boxes = [b for b in boxes if b.get("prompt") and b["prompt"] != _DEFAULT_PROMPT]
    lines += ["## Why", ""]
    if why_boxes:
        for b in why_boxes:
            lines.append(f'- **{b["title"]}**: {b["prompt"]}')
    else:
        lines.append("*No module intent defined yet — add prompts to canvas boxes.*")
    lines.append("")

    # ------------------------------------------------------------------ #
    #  What — modules by permission type                                  #
    # ------------------------------------------------------------------ #
    solid_boxes = [b for b in boxes if b.get("type") == "solid"]
    dotted_boxes = [b for b in boxes if b.get("type") == "dotted"]

    lines += ["## What", ""]
    if solid_boxes:
        lines.append("**Locked modules** (agent requires permission to edit):")
        for b in solid_boxes:
            files: list = b.get("linkedFiles") or []
            suffix = f' — `{", ".join(files)}`' if files else ""
            lines.append(f'- {b["title"]}{suffix}')
        lines.append("")
    if dotted_boxes:
        lines.append("**Agent-editable modules**:")
        for b in dotted_boxes:
            files = b.get("linkedFiles") or []
            suffix = f' — `{", ".join(files)}`' if files else ""
            lines.append(f'- {b["title"]}{suffix}')
        lines.append("")
    if not boxes:
        lines += ["*No modules on canvas yet.*", ""]

    # ------------------------------------------------------------------ #
    #  Dataflow — arrows                                                  #
    # ------------------------------------------------------------------ #
    box_map: dict = {b["id"]: b["title"] for b in boxes}

    lines += ["## Dataflow", ""]
    if arrows:
        for a in arrows:
            frm = box_map.get(a.get("fromBox", ""), "?")
            to = box_map.get(a.get("toBox", ""), "?")
            label_part = f' `{a["label"]}`' if a.get("label") else ""
            lines.append(f"- {frm} → {to}{label_part}")
    else:
        lines.append("*No data flows defined yet.*")
    lines.append("")

    # ------------------------------------------------------------------ #
    #  How — tasks by column                                              #
    # ------------------------------------------------------------------ #
    lines += ["## How", ""]
    for col_key in ("todo", "doing", "testing", "done"):
        col_tasks = [t for t in tasks if t.get("column") == col_key]
        if col_tasks:
            lines.append(f'**{_COLUMN_LABELS[col_key]}**')
            for t in col_tasks:
                status = t.get("verificationStatus", "pending")
                check = "✓" if status == "passed" else ("✗" if status == "failed" else "○")
                desc = t.get("description") or ""
                desc_part = f" — {desc}" if desc else ""
                lines.append(f'- {check} {t["title"]}{desc_part}')
            lines.append("")
    if not tasks:
        lines += ["*No tasks defined yet.*", ""]

    # ------------------------------------------------------------------ #
    #  Outcome — counters                                                 #
    # ------------------------------------------------------------------ #
    done_count = sum(
        1 for t in tasks
        if t.get("column") == "done" and t.get("verificationStatus") == "passed"
    )
    open_count = sum(1 for t in tasks if t.get("column") != "done")
    solid_count = len(solid_boxes)
    dotted_count = len(dotted_boxes)
    arrow_count = len(arrows)
    labeled_count = sum(1 for a in arrows if a.get("label"))

    lines += [
        "## Outcome",
        "",
        f"- {done_count} task(s) shipped · {open_count} open",
        f"- {solid_count} locked module(s) · {dotted_count} agent-editable",
        f"- {arrow_count} data flow(s) · {labeled_count} labeled",
        "",
    ]

    return "\n".join(lines)
