"""
openfde/prs.py — Land as PR v1 (episode → branch → GitHub pull request via local `gh`).

*OpenFDE owns the local commits and the receipts; the PR is how that record meets the
team.* A landed episode — clean title, story summary, linked issue intent, clustered
commits, changed files, Verify Gate evidence — becomes a branch + pull request whose
description IS the episode's story. Manual action only in v1: nothing auto-PRs.

The chain this completes:
    Issue / prompt intent → Episode → Verify evidence → Commit → **Branch → PR** →
        Story/OpenPM evidence

Deliberately local-CLI based (like ``issue_intents``): plain ``git`` for branch/push,
``gh pr create`` for the PR — no GitHub API client, no OAuth, no webhooks. All
subprocess calls go through one injectable runner so every behavior is testable
without a network. Guardrails: clean worktree required, idempotent when the episode
already carries ``pr.url``, an **already-merged guard** (a head commit reachable from
the remote default branch returns "no PR needed" instead of pushing a no-diff branch),
and structured errors (gh missing/unauthenticated, push or PR failure) that never
mutate the episode.

v1.1 adds :func:`pr_readiness` — the same policy as a deterministic, read-only
**verdict** (ready / blocked / created, with receipts and blockers), so the UI can
show "Ready to ship" before anyone clicks. Evidence decides; an LLM may narrate
readiness someday, but never decides it.
"""

import re
import shutil
import subprocess
from datetime import datetime, timezone

_PR_TIMEOUT = 60                      # network ops (push / gh) get a longer leash
_MAX_BODY_FILES = 30
_MAX_SLUG = 40
_PR_URL_RE = re.compile(r"https://github\.com/[\w.-]+/[\w.-]+/pull/(\d+)")


def branch_slug(episode: dict) -> str:
    """Predictable branch name: ``openfde/p25-verify-gate-evidence``."""
    tag = re.sub(r"[^a-z0-9]+", "", (episode.get("tag") or "ep").lower()) or "ep"
    title = (episode.get("title") or "episode").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", title).strip("-")[:_MAX_SLUG].strip("-")
    return f"openfde/{tag}-{slug or 'episode'}"


def build_pr_text(episode: dict) -> tuple:
    """(title, markdown body) — the PR description IS the episode's story + receipts.

    Body sections (each only when present): summary, linked GitHub issue intent,
    commits (with their durable per-commit titles), changed files (capped), and the
    Verify Gate evidence per check. Ends with the OpenFDE attribution note.
    """
    title = (episode.get("title") or episode.get("tag") or "OpenFDE change").strip()
    tag = episode.get("tag") or ""
    head = f"## {tag} · {title}" if tag else f"## {title}"
    lines = [head, ""]
    if episode.get("summary"):
        lines += [episode["summary"].strip(), ""]

    src = episode.get("intentSource") or {}
    if src.get("provider") == "github" and src.get("issueNumber") is not None:
        ref = f"**Issue:** #{src['issueNumber']}"
        if src.get("url"):
            ref += f" — {src['url']}"
        lines += [ref, ""]

    meta = episode.get("commitMeta") or {}
    shas = [s for s in (episode.get("commitShas") or []) if s]
    if shas:
        lines.append("**Commits:**")
        for sha in shas:
            t = (meta.get(sha) or {}).get("title") or ""
            lines.append(f"- `{sha[:7]}`" + (f" — {t}" if t else ""))
        lines.append("")

    files = [f for f in (episode.get("files") or []) if f]
    if files:
        lines.append(f"**Files ({len(files)}):**")
        lines += [f"- `{p}`" for p in files[:_MAX_BODY_FILES]]
        if len(files) > _MAX_BODY_FILES:
            lines.append(f"- … +{len(files) - _MAX_BODY_FILES} more")
        lines.append("")

    v = episode.get("verify") or {}
    if v:
        icon = {"passed": "✅", "failed": "❌", "skipped": "⏭️"}.get(v.get("status"), "•")
        lines.append(f"**Verification:** {icon} {v.get('status') or 'unknown'}")
        for c in v.get("checks") or []:
            ci = "✅" if c.get("status") == "passed" else "❌"
            label = c.get("label") or c.get("id") or "check"
            summary = c.get("summary") or ""
            lines.append(f"- {ci} {label}" + (f" — {summary}" if summary else ""))
        if v.get("status") == "skipped" and v.get("note"):
            lines.append(f"- {v['note']}")
        lines.append("")

    lines += ["---",
              f"_Generated by OpenFDE from episode {tag or episode.get('episodeId') or ''}"
              " — prompt, commits, and verification receipts recorded locally._"]
    return title, "\n".join(lines)


def _run(args, cwd, runner=None, timeout=_PR_TIMEOUT):
    run = runner or subprocess.run
    return run(list(args), cwd=str(cwd), capture_output=True, text=True, timeout=timeout)


def _base_ref(root, runner=None):
    """The remote default branch as a local tracking ref ('origin/main'), best-effort.

    Tries ``origin/HEAD`` (set by clone; absent on some repos), then falls back to
    ``origin/main`` / ``origin/master``. None when no remote-tracking ref exists —
    the guard is skipped and later steps fail with their own (push) error.
    """
    sr = _run(["git", "symbolic-ref", "--short", "refs/remotes/origin/HEAD"], root, runner)
    if _ok(sr) and (sr.stdout or "").strip():
        return (sr.stdout or "").strip()
    for cand in ("origin/main", "origin/master"):
        rp = _run(["git", "rev-parse", "--verify", "--quiet", cand], root, runner)
        if _ok(rp):
            return cand
    return None


def _ok(proc) -> bool:
    return getattr(proc, "returncode", 1) == 0


def _err(proc, fallback: str) -> str:
    msg = (getattr(proc, "stderr", "") or "").strip() or (getattr(proc, "stdout", "") or "").strip()
    return (msg or fallback)[:300]


def pr_readiness(root, episode: dict, *, runner=None, which=None, _ctx=None) -> dict:
    """Deterministic, **read-only** ready-for-PR verdict for an episode.

    Evidence + policy decide readiness — never an LLM. Mirrors the guards
    ``create_episode_pr`` enforces, without creating, pushing, or calling gh:

      - ``created`` — the episode already carries ``pr.url`` (action: open it).
      - ``blocked`` — any of: operational/meta episode, no landed commits, dirty
        worktree, verification failed, verification missing/skipped while the repo
        HAS checks configured (conservative v1.1), head commit already reachable
        from the remote default branch, gh CLI not installed.
      - ``ready`` — clean tree + landed commits + required checks passed + head not
        on base; ``reasons`` lists the receipts ("1 landed commit", "worktree
        clean", "unit tests passed", …).

    gh *auth* is deliberately NOT checked here (slow-ish; creation re-checks and
    can still fail then). Readiness reads local refs only — no fetch.

    Args:
        root: Path — repository root.
        episode: dict — the episode to judge.
        runner: optional subprocess.run stand-in (tests).
        which: optional shutil.which stand-in (tests).
        _ctx: optional shared batch context — {"clean": bool, "base": str|None,
            "on_base": (sha)->bool, "gh_ok": bool} — so a caller judging many
            episodes pays for `git status`/base resolution once.

    Returns:
        dict — {status: ready|blocked|created, suggestedAction: create_pr|
            fix_and_rerun|open_pr, reasons: [...], blockedBy: [...], pr?}.
    """
    existing = episode.get("pr") or {}
    if existing.get("url"):
        num = existing.get("number")
        return {"status": "created", "suggestedAction": "open_pr",
                "reasons": [f"PR #{num} already created" if num else "PR already created"],
                "blockedBy": [], "pr": existing}

    reasons, blocked = [], []

    from openfde.prompt_story import is_operational_episode
    if is_operational_episode(episode):
        blocked.append("operational/meta episode — not a product change")

    shas = [s for s in (episode.get("commitShas") or []) if s]
    if shas:
        reasons.append(f"{len(shas)} landed commit{'s' if len(shas) != 1 else ''}")
    else:
        blocked.append("no landed commits")

    if _ctx is not None:
        clean = _ctx.get("clean")
    else:
        st = _run(["git", "status", "--porcelain"], root, runner)
        clean = _ok(st) and not (st.stdout or "").strip()
    if clean:
        reasons.append("worktree clean")
    else:
        blocked.append("worktree has uncommitted files")

    v = episode.get("verify") or {}
    vstatus = v.get("status")
    if vstatus == "passed":
        for c in (v.get("checks") or []):
            label = (c.get("label") or c.get("id") or "check").lower()
            reasons.append(f"{label} {c.get('status') or 'passed'}")
    elif vstatus == "failed":
        blocked.append("verification failed")
    else:                                   # missing or skipped — conservative,
        from openfde.verify import discover_checks      # unless nothing is configured
        if discover_checks(root):
            blocked.append("verification has not run — run checks first")
        else:
            reasons.append("no checks configured — verification skipped")

    if shas:                                # on-base guard needs a head commit
        head_sha = shas[-1]
        if _ctx is not None:
            base, on_base = _ctx.get("base"), _ctx.get("on_base")
            already = bool(base and on_base and on_base(head_sha))
        else:
            base = _base_ref(root, runner)
            anc = _run(["git", "merge-base", "--is-ancestor", head_sha, base],
                       root, runner) if base else None
            already = bool(base and anc is not None and _ok(anc))
        if already:
            blocked.append(f"commit {head_sha[:7]} already on {base} — no PR needed")

    gh_ok = _ctx.get("gh_ok") if _ctx is not None else bool((which or shutil.which)("gh"))
    if not gh_ok:
        blocked.append("gh CLI not installed")

    if blocked:
        return {"status": "blocked", "suggestedAction": "fix_and_rerun",
                "reasons": [], "blockedBy": blocked}
    return {"status": "ready", "suggestedAction": "create_pr",
            "reasons": reasons, "blockedBy": []}


def create_episode_pr(root, episode: dict, *, runner=None, now=None) -> dict:
    """Branch from the episode's newest commit, push, and open a GitHub PR via `gh`.

    Guardrails (v1): requires landed commit evidence and a **clean worktree**;
    idempotent — an episode already carrying ``pr.url`` returns it untouched;
    a head commit **already reachable from the remote default branch** is refused
    ("no PR needed") before anything is created or pushed; gh missing/
    unauthenticated or any git/gh failure returns a structured error
    (``{ok: False, error, branch?, pushed?}``) and never invents PR metadata.
    The episode dict is NOT mutated here — the caller stores ``pr`` on success.

    Args:
        root: Path — repository root.
        episode: dict — a landed episode (tag/title/summary/commitShas/commitMeta/
            files/verify/intentSource feed the branch name and PR body).
        runner: optional subprocess.run stand-in (tests).
        now: optional ISO timestamp override (tests).

    Returns:
        dict — {ok: True, pr, existing} | {ok: False, error, branch?, pushed?}.
    """
    existing = episode.get("pr") or {}
    if existing.get("url"):
        return {"ok": True, "pr": existing, "existing": True}

    shas = [s for s in (episode.get("commitShas") or []) if s]
    if not shas:
        return {"ok": False, "error": "episode has no landed commits to put in a PR"}

    st = _run(["git", "status", "--porcelain"], root, runner)
    if not _ok(st):
        return {"ok": False, "error": _err(st, "git status failed")}
    if (st.stdout or "").strip():
        return {"ok": False,
                "error": "worktree is dirty — land or stash changes before Land as PR (v1 requires a clean tree)"}

    head_sha = shas[-1]                            # newest landed commit = the PR head

    # Already-merged guard: a commit reachable from the remote default branch would
    # make an empty/no-diff PR (or a late gh failure after a junk branch push). Local
    # remote-tracking refs are safe for this: reachability at last fetch/push implies
    # reachability now; a stale miss just falls through to gh's own error later.
    base = _base_ref(root, runner)
    if base:
        anc = _run(["git", "merge-base", "--is-ancestor", head_sha, base], root, runner)
        if _ok(anc):
            return {"ok": False,
                    "error": f"episode commit {head_sha[:7]} is already on {base} — "
                             "its changes are merged into the base branch; no PR needed"}

    try:
        auth = _run(["gh", "auth", "status"], root, runner)
    except FileNotFoundError:
        return {"ok": False, "error": "gh CLI not installed — Land as PR rides the local gh"}
    if not _ok(auth):
        return {"ok": False, "error": "gh not authenticated: " + _err(auth, "run `gh auth login`")}
    branch = branch_slug(episode)
    rp = _run(["git", "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"], root, runner)
    if _ok(rp):
        if (rp.stdout or "").strip() != head_sha:  # name taken by something else → disambiguate
            branch = f"{branch}-{head_sha[:7]}"
            rp2 = _run(["git", "rev-parse", "--verify", "--quiet", f"refs/heads/{branch}"], root, runner)
            if _ok(rp2) and (rp2.stdout or "").strip() != head_sha:
                return {"ok": False, "error": f"branch {branch} already exists on a different commit"}
            if not _ok(rp2):
                mk = _run(["git", "branch", branch, head_sha], root, runner)
                if not _ok(mk):
                    return {"ok": False, "error": _err(mk, "git branch failed"), "branch": branch}
        # same commit → reuse the existing branch as-is
    else:
        mk = _run(["git", "branch", branch, head_sha], root, runner)
        if not _ok(mk):
            return {"ok": False, "error": _err(mk, "git branch failed"), "branch": branch}

    push = _run(["git", "push", "-u", "origin", branch], root, runner)
    if not _ok(push):
        return {"ok": False, "error": "push failed: " + _err(push, "git push failed"),
                "branch": branch, "pushed": False}

    title, body = build_pr_text(episode)
    try:
        pr = _run(["gh", "pr", "create", "--head", branch, "--title", title, "--body", body],
                  root, runner)
    except FileNotFoundError:
        return {"ok": False, "error": "gh CLI not installed", "branch": branch, "pushed": True}
    if not _ok(pr):
        return {"ok": False, "error": "gh pr create failed: " + _err(pr, "unknown gh error"),
                "branch": branch, "pushed": True}

    out = (pr.stdout or "").strip()
    m = _PR_URL_RE.search(out)
    if not m:
        return {"ok": False, "error": f"could not parse PR URL from gh output: {out[:200]}",
                "branch": branch, "pushed": True}
    return {"ok": True, "existing": False, "pr": {
        "provider": "github",
        "number": int(m.group(1)),
        "url": m.group(0),
        "branch": branch,
        "title": title,
        "state": "OPEN",
        "createdAt": now or datetime.now(timezone.utc).isoformat(),
    }}
