"""
openfde/report.py — deterministic REPORT.md generator (Step 18).

Folds the project's why, the project.md conversation ledger, OpenFDE timeline
events, git commits, and execution runs into a single end-of-run report. No
LLM — purely a structured roll-up of what already happened.
"""

import logging

logger = logging.getLogger("openfde.report")

_MAX_LEDGER = 30
_MAX_EVENTS = 40
_MAX_COMMITS = 40
_MAX_RUNS = 20

_ROLE_LABEL = {"architect": "Architect", "sr_dev": "Senior Dev", "verifier": "Verifier", "human": "Human"}


def generate_report(project: dict, ledger: list, events: list, commits: list, runs: list) -> str:
    """Render REPORT.md from project memory, ledger, events, commits, and runs.

    Args:
        project: dict — project metadata {name, description, entries}.
        ledger: list[dict] — project.md ledger entries (oldest-first).
        events: list[dict] — OpenFDE timeline events (oldest-first).
        commits: list[dict] — git commits newest-first (see git_timeline).
        runs: list[dict] — execution run records (latest-first).

    Returns:
        str — complete REPORT.md markdown document.
    """
    lines: list = []
    a = lines.append

    name = (project or {}).get("name") or "OpenFDE Project"
    desc = (project or {}).get("description") or ""

    a(f"# {name} — Report")
    a("")
    a("_Generated by OpenFDE — deterministic roll-up of project memory, commits, and runs._")
    a("")

    # ── Problem Statement / Why ──────────────────────────────────────────── #
    a("## Problem Statement / Why")
    a("")
    if desc:
        a(desc)
        a("")
    why_entries = [e for e in (ledger or []) if e.get("role") == "architect" and (e.get("summary") or e.get("title"))]
    if why_entries:
        for e in why_entries[:5]:
            a(f"- {e.get('title') or e.get('summary')}")
        a("")
    if not desc and not why_entries:
        a("_No problem statement recorded yet._")
        a("")

    # ── Conversation ledger ──────────────────────────────────────────────── #
    a("## Conversation Ledger")
    a("")
    if not ledger:
        a("_No ledger entries._")
        a("")
    else:
        for e in ledger[-_MAX_LEDGER:]:
            role = _ROLE_LABEL.get(e.get("role"), e.get("role") or "note")
            ts = (e.get("timestamp") or "")[:19].replace("T", " ")
            title = e.get("title") or e.get("summary") or ""
            a(f"- **{role}** ({ts}): {title}")
        a("")

    # ── Git history ──────────────────────────────────────────────────────── #
    a("## Git History")
    a("")
    if not commits:
        a("_No commits yet._")
        a("")
    else:
        for c in commits[:_MAX_COMMITS]:
            ts = (c.get("timestamp") or "")[:19].replace("T", " ")
            a(f"- `{c.get('shortSha', '')}` {c.get('summary', '')} — {c.get('author', '')} ({ts})")
        a("")

    # ── Execution runs ───────────────────────────────────────────────────── #
    a("## Execution Runs")
    a("")
    if not runs:
        a("_No runs recorded._")
        a("")
    else:
        mark = {"passed": "✅", "failed": "❌", "running": "▶", "planning": "…"}
        for r in runs[:_MAX_RUNS]:
            status = r.get("status", "?")
            n = len(r.get("scopedBoxIds", []))
            started = (r.get("startedAt") or "")[:19].replace("T", " ")
            a(f"- {mark.get(status, '·')} `{r.get('runId', '')}` — {status}, {n} module(s) in scope ({started})")
        a("")

    # ── Timeline ─────────────────────────────────────────────────────────── #
    a("## Timeline (recent)")
    a("")
    if not events:
        a("_No events recorded._")
        a("")
    else:
        for e in events[-_MAX_EVENTS:]:
            ts = (e.get("timestamp") or "")[:19].replace("T", " ")
            etype = e.get("type", "event")
            detail = (e.get("payload") or {}).get("detail") or ""
            a(f"- `{ts}` **{etype}** {detail}".rstrip())
        a("")

    # ── Outcome ──────────────────────────────────────────────────────────── #
    a("## Outcome")
    a("")
    passed = sum(1 for r in (runs or []) if r.get("status") == "passed")
    failed = sum(1 for r in (runs or []) if r.get("status") == "failed")
    a(f"- {len(commits or [])} commit(s), {len(runs or [])} run(s) "
      f"({passed} passed, {failed} failed), {len(ledger or [])} ledger entr(ies).")
    a("")

    return "\n".join(lines)
